import Head from 'next/head'
import { Header } from '@/components/header/Header'
import { Pad } from '@/components/pad/Pad'

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Pad />
    </>
  )
}
